---
title: "Publication"
format: html
---

1.  Zou Xiang, Zhou Hao, Liu Mianyu, Qiang Guangfeng, Dai Ping, Sui Juan, Kong Jie, Luo Kun, Meng Xianhong, Xing Qun, Fu Qiang, **Luan Sheng**. A genome-structure adaptive framework for ROH-based inbreeding estimation in Penaeus vannamei. Scientific Reports, 2026, 16, 1, 6769. <https://doi.org/10.1038/s41598-026-37622-8>.

2.  Liu Mianyu, Fu Qiang, Wang Ping, Qiang Guangfeng, Luo Kun, Chen Baolong, **Luan Sheng**, Kong Jie, Xu Pao. Pedigree-assisted genotype imputation enables cost-effective genomic prediction in Penaeus vannamei. Scientific Reports, 2026, 16, 1, 16656. <https://doi.org/10.1038/s41598-026-47716-y>.

3.  **Luan Sheng**, Kong Jie, Xia Zhenglong, Kang Ziyi, Qiang Guangfeng, Luo Kun, Sui Juan. visPedigree: a comprehensive R package for tidying, analyzing, and visualizing breeding pedigrees. Bioinformatics Advances, 2026. <https://doi.org/10.1093/bioadv/vbag210>.

4.  Fu Qiang, Qiang Guangfeng, Wang Ping, Liu Mianyu, Luo Kun, Chen Baolong, Meng Xianhong, Zou Xiang, Dai Ping, Liu Junyu, Zhang Shiwei, Kong Jie, **Luan Sheng**. Development and Applications of a 1K SNP Panel for Whiteleg Shrimp: From Pedigree Reconstruction to Genomic Selection. International Journal of Molecular Sciences, 2026, 27, 11, 4665. <https://doi.org/10.3390/ijms27114665>.

5.  Lyu Tianzan, Dai Ping, Zhang Min, Yan Maocang, Qiang Guangfeng, Fu Qiang, Luo Kun, Meng Xianhong, Chen Baolong, Sui Juan, Li Xupeng, Liu Junyu, Liu Mianyu, Tan Jian, Cao Jiawang, Kong Jie, Zhou Hao, **Luan Sheng**. Local Enrichment of Multi-SNP Markers Improves Genomic Prediction from Low-Density Genotyping in Pacific White Shrimp. International Journal of Molecular Sciences, 2026, 27, 14, 6202. <https://doi.org/10.3390/ijms27146202>.

6.  张士薇，代平，高广春，孟宪红，罗坤，隋娟，谭建，傅强，曹家旺，陈宝龙，李旭鹏，强光峰，邢群，戚云辉，孔杰，**栾生.** 基于深度学习算法的凡纳滨对虾生长表型测定系统研发及应用. 水产学报, 2025, 49, 059117--059117. <https://doi.org/10.11964/jfc.20240714612>.

7.  Kang Ziyi, Kong Jie, Li Qi, Sui Juan, Dai Ping, Luo Kun, Meng Xianhong, Chen Baolong, Cao Jiawang, Tan Jian, Fu Qiang, Wang Zhaoxin, **Luan Sheng**. Genomic selection for hard-to-measure traits in aquaculture: Challenges in balancing genetic gain and diversity. Aquaculture, 2025, 606, 742576. <https://doi.org/10.1016/j.aquaculture.2025.742576>.

8.  Lv Tianzan, Xia Yan, Tan Jian, Fu Qiang, Luo Kun, Meng Xianhong, Chen Baolong, Chen Meijia, Sui Juan, Dai Ping, Li Xupeng, Liu Junyu, Liu Mianyu, Cao Jiawang, Xing Qun, Qiang Guangfeng, Kong Jie, Zhou Hao, **Luan Sheng**. Multi-marker GWAS and variant-specific genomic prediction for growth traits in Pacific white shrimp. Scientific Reports, 2025, 15, 1, 42103. <https://doi.org/10.1038/s41598-025-26048-3>.

9.  Kang Ziyi, Kong Jie, Li Qi, Sui Juan, Dai Ping, Luo Kun, Meng Xianhong, Chen Baolong, Cao Jiawang, Tan Jian, Fu Qiang, Xing Qun, **Luan Sheng**. Genomic selection strategies to overcome genotype by environment interactions in biosecurity-based aquaculture breeding programs. Genetics Selection Evolution, 2025, 57, 1, 2. <https://doi.org/10.1186/s12711-025-00949-3>.

10.  Zhou Hao, Qiang Guangfeng, Xia Yan, Tan Jian, Fu Qiang, Luo Kun, Meng Xianhong, Chen Baolong, Chen Meijia, Sui Juan, Dai Ping, Li Xupeng, Liu Mianyu, Xing Qun, Kong Jie, **Luan Sheng**. Copy Number Variations in Short Tandem Repeats Modulate Growth Traits in Penaeid Shrimp Through Neighboring Gene Regulation. Animals, 2025, 15, 2, 262. <https://doi.org/10.3390/ani15020262>.

11.  Zhang Shiwei, Kong Jie, Tan Jian, Meng Xianhong, Dai Ping, Cao Jiawang, Luo Kun, Liu Mianyu, Xing Qun, Tian Yi, Sui Juan, **Luan Sheng**. Multi-Trait Genomic Prediction of Meat Yield in Pacific Whiteleg Shrimp (Penaeus vannamei). Animals, 2025, 15, 8, 1165. <https://doi.org/10.3390/ani15081165>.

12.  Gao Siqi, Xia Yan, Kong Jie, Meng Xianhong, Luo Kun, Sui Juan, Dai Ping, Tan Jian, Li Xupeng, Cao Jiawang, Chen Baolong, Fu Qiang, Xing Qun, Tian Yi, Liu Junyu, **Luan Sheng**. Genomic Evaluation of Harvest Weight Uniformity in Penaeus vannamei Under a 3FAM Design Incorporating Indirect Genetic Effect. Biology, 2025, 14, 4, 328. <https://doi.org/10.3390/biology14040328>.

13.  Kang Ziyi, Kong Jie, Sui Juan, Dai Ping, Luo Kun, Meng Xianhong, Liu Junyu, Chen Baolong, Cao Jiawang, Tan Jian, Fu Qiang, Li Qi, **Luan Sheng**. Optimal open nucleus breeding system for long-term genetic gain in the Pacific white shrimp using genomic selection. Aquaculture, 2024, 586, 740760. <https://doi.org/10.1016/j.aquaculture.2024.740760>.

14.  Liu Mianyu, Li Xupeng, Kong Jie, Meng Xianhong, Luo Kun, Sui Juan, Dai Ping, Tan Jian, Cao Jiawang, Chen Baolong, Wang Hongjie, **Luan Sheng**. Genomic selection of resistance to acute hepatopancreatic necrosis disease in Litopenaeus vannamei. Aquaculture, 2024, 596, 741828. <https://doi.org/10.1016/j.aquaculture.2024.741828>.

15.  Dai Ping, Li Dongyan, Sui Juan, Kong Jie, Meng Xianhong, **Luan Sheng**. Prediction of meat yield in the Pacific whiteleg shrimp Penaeus vannamei. Aquaculture, 2023, 577, 739914. <https://doi.org/10.1016/j.aquaculture.2023.739914>.

16.  Liu Mianyu, Dai Ping, Kong Jie, Meng Xianhong, Sui Juan, Luo Kun, Chen Baolong, Fu Qiang, Cao Baoxiang, Cao Jiawang, **Luan Sheng**. Assessing accuracy of genomic breeding values of selection candidates under biosecurity restrictions by progeny testing in Chinese shrimp Fenneropenaeus chinensis. Aquaculture, 2022, 566, 739181. <https://doi.org/10.1016/j.aquaculture.2022.739181>.

17.  孙犁, 卢霞, 孔杰, 孟宪红, 闫允君, 李波波, 仲伟鹏, 陈宝龙, 曹宝祥, 罗坤, **栾生**. 中国明对虾calcineurin B基因的克隆及其在竞争行为中作用的初探. 水产学报, 2020, 44(1):11~20.

18.  Kong Zhangwei, Kong Jie, Hao Dongchun, Lu Xia, Tan Jian, Meng Xianhong, Luo Kun, Cao Baoxiang, Sui Juan, Li Xupeng, **Luan Sheng**. Reducing the Common Environmental Effect on Litopenaeus vannamei Body Weight by Rearing Communally at Early Developmental Stages and Using a Reconstructed Pedigree. Journal of Ocean University of China, 2020, 19, 4, 923-930. <https://doi.org/10.1007/s11802-020-4324-5>.

19.  Dai Ping, Kong Jie, Liu Junyu, Lu Xia, Sui Juan, Meng Xianhong, **Luan Sheng**. Evaluation of the utility of genomic information to improve genetic evaluation of feed efficiency traits of the Pacific white shrimp Litopenaeus vannamei. Aquaculture, 2020, 527, 735421. <https://doi.org/10.1016/j.aquaculture.2020.735421>.

20.  Liu Junyu, Yang Guoliang, Kong Jie, Xia Zhenglong, Sui Juan, Tang Qiongying, Luo Kun, Dai Ping, Lu Xia, Meng Xianhong, **Luan Sheng**. Using single-step genomic best linear unbiased prediction to improve the efficiency of genetic evaluation on body weight in Macrobrachium rosenbergii. Aquaculture, 2020, 528, 735577. <https://doi.org/10.1016/j.aquaculture.2020.735577>.

21.  **Luan Sheng**, Qiang Guangfeng, Cao Baoxiang, Luo Kun, Meng Xianhong, Chen Baolong, Kong Jie. Feed competition reduces heritable variation for body weight in Litopenaeus vannamei. Genetics Selection Evolution, 2020, 52, 1, 45. <https://doi.org/10.1186/s12711-020-00565-3>.

22.  刘峻宇, 杨国梁, 孔杰, 夏正龙, 罗坤, 唐琼英, 卢霞, 孟宪红, 李景芬, **栾生**. 罗氏沼虾开放和闭锁核心育种群生长和存活性能分析. 中国水产科学, 2019, 26(5):861-868.

23.  刘峻宇, 刘均辉, 孔杰, 代平, 于洋, 孟宪红, 罗坤, 曹宝祥, 陈宝龙, **栾生***,* **高焕**. 凡纳滨对虾SNP标记开发与家系亲缘关系验证分析. 渔业科学进展, 2019, <https://doi.org/10.19663/j.issn2095-9869.20191022001>.

24.  Sui Juan, **Luan Sheng**, Yang Guoliang, Xia Zhenglong, Luo Kun, Tang Qiongying, Lu Xia, Meng Xianhong, Kong Jie. Genetic parameters and selection response for the harvest body weight of the giant freshwater prawn (*Macrobrachium rosenbergii*) in a breeding program in China. PLOS ONE, 2019, 14(8): e0218379. <https://doi.org/10.1371/journal.pone.0218379>.

25.  **栾生**, 仲伟鹏, 谭健, 罗坤, 陈宝龙, 孔杰. 凡纳滨对虾收获体重大规模家系选择效果的计算机模拟分析. 水产学报, 2018, 42(10): 1582-1588.

26.  仲伟鹏, 罗坤, 孟宪红, 陈宝龙, 隋娟, 孔杰, 曹宝祥, 邢群, **栾生**. 限制投喂环境下中国对虾体重的间接遗传效应分析. 中国水产科学, 2018, 25(6):1245-1251.

27.  Dai Ping, Kong Jie, Wang Sen, Lu Xia, Luo Kun, Cao Baoxiang, Meng Xianhong, **Luan Sheng**. Identification of SNPs associated with residual feed intake from the muscle of Litopenaeus vannamei using bulk segregant RNA-seq. Aquaculture, 2018, 497, 56-63. <https://doi.org/10.1016/j.aquaculture.2018.07.045>.

28.  Dai Ping, Kong Jie, Meng Xianhong, Luo Kun, Lu Xia, Chen Baolong, Cao Baoxiang, **Luan Sheng**. Genotype by environment interaction for feed efficiency trait of the juvenile Pacific white shrimp Litopenaeus vannamei held in individuals vs. in groups. Aquaculture, 2018, 500, 506-513. <https://doi.org/10.1016/j.aquaculture.2018.10.063>.

29.  TAN Jian, KONG Jie, LUO Kun, CAO Baoxiang, LIU Ning, MENG Xianghong, GUO Zhaojia, XU Shengyu, and **Luan Sheng***.* Genetic parameter estimation of reproductive traits of *Litopenaeus vannamei*. Journal of Ocean University of China. 2017, 16(1): 161-167.

30.  强光峰, 杨国梁, 陈雪峰, 孔杰, 夏正龙, 高强, 罗坤, **栾生**. 罗氏沼虾高世代育种群体收获体重加性和显性遗传效应. 中国水产科学, 2017, 24(5):1027-1034.

31.  Lu Xia, Kong Jie, Meng Xianhong, Cao Baoxiang, Luo Kun, Dai Ping, **Luan Sheng**. Identification of SNP markers associated with tolerance to ammonia toxicity by selective genotyping from de novo assembled transcriptome in Litopenaeus vannamei. Fish & Shellfish Immunology, 2017, 73, 158-166. <https://doi.org/10.1016/j.fsi.2017.12.005>.

32.  Sui Juan, **Luan Sheng**, Luo Kun, Meng Xianhong, Cao Baoxiang, Liu Ning, Li Wenjia, Lu Xia, Chai Zhan, Kong Jie. Genetic parameters and response to selection of harvest body weight of the Chinese shrimp *Fenneropenaeus chinensis* after five generations of multi-trait selection. Aquaculture, 2016, 452: 134--141.

33.  Sui Juan, **Luan Sheng**, Yang Guoliang, Chen Xuefeng, Luo Kun, Gao Qiang, Wang Junyi, Hu Honglang, Kong Jie. Impact of pedigree depth and inclusion of historical data in the estimation of variance components and breeding values in *Macrobrachium rosenbergii*. Aquaculture, 2016, 464:80-86.

34.  Lu Xia, **Luan Sheng**, Hu LongYang, Mao Yong, Tao Ye, Zhong ShengPing, Kong Jie. High resolution genetic linkage mapping, high temperature tolerance and growth related quantitative trait locus (QTL) identification in *Marsupenaeus japonicus*. Molecular Genetics and Genomics, 2016, <DOI:10.1007/S00438-016-1192-1>.

35.  Sui Juan, **Luan Sheng**, Luo Kun, Meng Xianhong, Lu Xia, Cao Baoxiang, Li Wenjia, Chai Zhan, Liu Ning, Xu Shengyu, Kong Jie*.* Genetic parameters and response to selection for harvest body weight of pacific white shrimp, *Litopenaeus vannamei*. Aquaculture Research, 2015, 1-9. <DOI:10.1111/are.12729>.

36.  Lu Xia, **Luan Sheng**, Hu Longyang, Mao Yong, Kongjie. Genome-wide mining, characterization, and development of microsatellite markers in *Marsupenaeus japonicus* by genome survey sequencing. Chinese Journal of Oceanology and limnology, 2015, DOI: 10.1007/s00343-016-5250-7.

37.  **Luan Sheng**, Luo Kun, Chai Zhan, Cao Baoxiang, Meng Xianhong, Lu Xia, Liu Ning, Xu Shengyu, Kong Jie. An analysis of indirect genetic effects on adult body weight of the Pacific white shrimp Litopenaeus vannamei at low rearing density. Genetics Selection Evolution, 2015, 47, 1, 95. <https://doi.org/10.1186/s12711-015-0164-y>.

38.  **栾生**, 隋娟, 孟宪红, 罗坤, 曹宝祥, 孔杰. 最佳遗传贡献理论及其在水产动物选择育种中的应用前景. 渔业科学进展, 2014, 6(35):133-140.

39.  **栾生**, 罗坤, 阮晓红, 曹宝祥, 王浩, 杜学芳, 张凯, 孔杰. 凡纳滨对虾体重、存活性状的遗传参数和基因型与环境互作效应. 海洋与湖沼, 2013, 44(2): 445-452.

40.  **栾生**, 金武, 孔杰, 罗坤, 孟宪红, 张天时, 王清印. 中国对虾(*Fenneropenaeus chinensis*)多性状复合育种方案的遗传和经济评估. 海洋学报, 2013, 35(2):133-142.

41.  **Luan Sheng**, Yang Guoliang, Wang Junyi, Luo Kun, Chen Xuefeng, Gao Qiang, Hu Honglang, Kong Jie. Selection responses in survival of Macrobrachium rosenbergii after performing five generations of multi-trait selection for growth and survival. Aquaculture International, 2013, 22, 3, 993-1007. <https://doi.org/10.1007/s10499-013-9722-x>.

42.  **Luan Sheng**, Wang Junyi, Yang Guoliang, Luo Kun, Chen Xuefeng, Gao Qiang, Hu Honglang, Kong Jie. Genetic parameters of survival for six generations in the giant freshwater prawn Macrobrachium rosenbergii. Aquaculture Research, 2013, 46, 6, 1345-1355. <https://doi.org/10.1111/are.12287>.

43.  **Luan Sheng**, Yang Guoliang, Wang Junyi, Luo Kun, Zhang Yufei, Gao Qiang, Hu Honglang, Kong Jie. Genetic parameters and response to selection for harvest body weight of the giant freshwater prawn *Macrobrachium rosenbergii*. Aquaculture, 2012, 362-363(1-4):88-96.

44.  **栾生**, 边文冀, 邓伟, 胡红浪, 孔杰, 秦钦, 陈校辉, 钟立强, 黄太寿. 斑点叉尾鮰基础群体生长和存活性状遗传参数估计. 水产学报, 2012, 36(9): 1313-1321.

45.  **栾生**, 孔杰, 张天时, 罗坤, 杨翠华, 田燚, 王清印.基于表型值和育种值的中国对虾生长、抗逆性状相关分析.海洋水产研究, 2008, 29(3):14-20.

46.  **栾生**, 孔杰, 王清印, 高 焕, 王伟继, 张庆文.日本囊对虾(*Marsupenaeus japonicus*)基因组微卫星特征分析.自然科学进展, 2007, 17(6):731-740

47.  **栾生**, 孔杰, 王清印, 高 焕, 王伟继, 张庆文. 日本囊对虾基因组小卫星特征分析. 水产学报, 2007, 31(2) :88-95.

48.  **栾生**, 孔杰, 王清印. 日本囊对虾三个地理群体的多元异速生长分析. 海洋与湖沼, 2006, 38(Supp.):60-65.

49.  **栾生**, 孙慧玲, 孔杰. 刺参耳状幼体体长遗传力的估计. 中国水产科学, 2006, 13(3):378-383.

50.  **Luan Sheng**, Kong Jie, Wang Qing Yin. Genetic variation of wild and cultured populations of the Kuruma prawn Marsupenaeus japonicus (Bate 1888) using microsatellites. Aquaculture Research, 2006, 37, 8, 785-792. <https://doi.org/10.1111/j.1365-2109.2006.01491.x>.
